# Continuous Delivery Workflow
name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate with Docker
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/mle-challenge-api .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mle-challenge-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mle-challenge-api \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/mle-challenge-api \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated
